# set this to true if you don't want your players see version of CommandsEX when they type /cex
disableVersion: false

# set this to true if you don't want player commands to be logged in console
# example: [INFO] [Zathrus_Writer] /tploc 0 80 0
logCommands: true

# provide a list of CommandsEX commands that you want to completely disable from being used
disabledCommands: []