# set this to true if you don't want your players see version of CommandsEX when they type /cex
disableVersion: false

# set this to true if you don't want player commands to be logged in console
# example: [INFO] [Zathrus_Writer] /tploc 0 80 0
logCommands: true

# provide a list of CommandsEX commands that you want to completely disable from being used
disabledCommands: []

# default language to be used for all players until they switch
# this should be a valid ISO Language Code, or Language and Country code
# example: en, en_us, en_gb
defaultLang: en

# list of all languages that will be available to your users,
# should you decide to allow them to change their language on per-user basis
availableLangs: [en, sk]