author: Zathrus Writer
description: A set of commands and event handlers, built to per-request specs.
main: com.github.zathrus_writer.commandsex.CommandsEX
name: CommandsEX
load: postworld
version: 'Alpha 1.3'
website: http://dev.bukkit.org/server-mods/commandsex
permissions:
  cex.allowspamcommands:
    default: op
    description: Allows players to repeat same command multiple times in a short time period without being stopped. Useful for admin purposes.
  cex.reload:
    default: op
    description: Allows player to reload CommandsEX configuration from disk (/cex reload).
  cex.tp:
    default: op
    description: Allows player to teleport himself to another player (/tp Player) and also one player to another (/tp Player1 Player2).
    children:
      cex.tpto: true
  cex.tpto:
    default: op
    description: Allows player to teleport himself to another player. (/tpto).
  cex.tphere:
    default: op
    description: Allows player to teleport another player to himself. (/tphere).
  cex.tploc:
    default: op
    description: Allows player to teleport himself to a specified location (/tploc).
  cex.tpa:
    default: op
    description: Player may ask another player for permission to teleport to him (/tpa).
  cex.tpahere:
    default: op
    description: Player may ask another player to teleport to him (/tpahere).
  cex.tpaccept:
    default: op
    description: Player may accept a teleport request from another player (/tpaccept).
  cex.tpdeny:
    default: op
    description: Player may reject a teleport request from another player (/tpdeny).
  cex.back:
    default: op
    description: Allows a player to return to his last known location (/back).
  cex.lang:
    default: true
    description: Allows player to change their language and display list of available languages to change to.
  cex.spawn:
    default: true
    description: Allows player to instantly teleport to a spawn location.
  cex.setspawn:
    default: op
    description: Allows player to set server's spawn location.
  cex.sethome:
    default: true
    description: Allows player to set their home location in the given world.
  cex.home:
    default: true
    description: Allows player to visit their home or their friends' homes.
  cex.home.invite:
    default: true
    description: Allows player to invite and uninvite other players to/from their home.
  cex.home.list:
    default: true
    description: Allows player to list players that are invited to his home or homes this player is invited to.
  cex.home.listall:
    default: op
    description: Allows player to list all homes that are created on the server.
  cex.home.publicize:
    default: true
    description: Allows player to make their home private or public.
  cex.home.delete:
    default: true
    description: Allows player to delete their own home.
  cex.home.delete.all:
    default: op
    description: Allows player to delete any home.
  cex.home.iclear:
    default: op
    description: Allows player to clear all homes where players haven't been online in a given number of days.
    children:
      cex.hyes: true
  cex.hyes:
    default: op
    description: Allows player to confirm the /home iclear command and really delete all homes found by it.
  cex.home.tclear:
    default: op
    description: Allows player to teleport to first home where players haven't been online in a given number of days.
  cex.bypasshomequalify:
    default: op
    description: Player with this permission is not required to spend a fixed amount of time on the server before being allowed to set home.
  cex.bypassinvite:
    default: op
    description: Player with this permission can visit all homes without the need to be invited to them.
  cex.kick:
    default: op
    description: Allows player to kick other players from the server.
  cex.mute:
    default: op
    description: Allows player to mute other players.
  cex.unmute:
    default: op
    description: Allows player to unmute other players.
  cex.freeze:
    default: op
    description: Allows player to freeze and unfreeze other players.
  cex.warp.bypasslimits:
    default: op
    description: Player with this permission can create unlimited number of warps, regardless of config settings.
  cex.warp.create:
    default: op
    description: Allows player to create warps.
  cex.warp:
    default: true
    description: Allows player to use warps (i.e. teleport to them).
  cex.warp.any:
    default: op
    description: Allows player to visit both private and public warps.
  cex.warp.listprivate:
    default: op
    description: Allows player to list private warps.
  cex.warp.listpublic:
    default: true
    description: Allows player to list public warps.
  cex.warp.public:
    default: op
    description: Allows player to make warps public.
  cex.warp.private:
    default: op
    description: Allows player to make warps private.
  cex.warp.rename:
    default: op
    description: Allows player to rename warps.
  cex.warp.delete:
    default: true
    description: Allows player to delete his own warp points.
  cex.warp.delete.all:
    default: op
    description: Allows player to delete any warp point.
  Listener.replacechat:
    default: true
    description: Placeholder for event function that allows player chat text replacements.
  Listener.replaceplayercommand:
    default: true
    description: Placeholder for event function that allows player command replacements.
  Listener.savebackposition:
    default: true
    description: Placeholder for event function that saves last player position in the event of teleportation.
  Listener.replaceconsolecommand:
    default: true
    description: Placeholder for event function that allows server (console) command replacements.
  Init.Home:
    default: true
    description: Placeholder for initialization function used to import MyHome database file into CommandsEX.
  Init.Warps:
    default: true
    description: Placeholder for initialization function used to check and create warp points database.
commands:
  cex:
    description: Displays version information and allows getting/setting configuration options.
    usage: |
           /<command>
           /<command> config -> lists available options
           /<command> config get <option>
           /<command> cg <option>
           /<command> config set <option> [add|remove <value>]
           /<command> cs <option> [add|remove <value>]
  cex_tp:
    description: Teleports one player to another.
    usage:  /<command> <Player1> [Player2]
    permission: cex.tp
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tp,tele,teleport,tp2p]
  cex_tpto:
    description: Teleports the active player to another player.
    usage: /<command> <Player>
    permission: cex.tpto
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tpto]
  cex_tphere:
    description: Teleports another player to the active player.
    usage: /<command> <Player>
    permission: cex.tphere
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tphere]
  cex_tploc:
    description: Teleports the player to the given XYZ coordinates.
    usage: |
           /<command> <X> <Y> <Z>
           /<command> <X,Y,Z>
    permission: cex.tploc
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tploc]
  cex_tpa:
    description: Asks a player for permission to teleport to him.
    usage: /<command> <Player>
    permission: cex.tpa
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tpa,call,tpask]
  cex_tpahere:
    description: Requests another player to teleport to you.
    usage: /<command> <Player>
    permission: cex.tpahere
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tpahere]
  cex_tpaccept:
    description: Accepts /tpa or /tpahere request for a specified player.
    usage: /<command> <Player>
    permission: cex.tpaccept
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tpaccept,tpyes]
  cex_tpdeny:
    description: Rejects /tpa or /tpahere request for a specified player.
    usage: /<command> <Player>
    permission: cex.tpdeny
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tpdeny,tpno]
  cex_back:
    description: Returns a player to his last know location.
    usage: /<command>
    permission: cex.back
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [back]
  cex_lang:
    description: Displays list of available languages or changes language for the player.
    usage: /<command> [language]
    permission: cex.lang
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [lang]
  cex_spawn:
    description: Teleports a player to server's spawn location.
    usage: /<command>
    permission: cex.spawn
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [spawn]
  cex_setspawn:
    description: Sets the server's spawn location.
    usage: /<command>
    permission: cex.setspawn
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [setspawn]
  cex_sethome:
    description: Sets player's home location in the current world.
    usage: /<command>
    permission: cex.sethome
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [sethome]
  cex_home:
    description: Sets player's home location, teleports to home locations and allows for homes administration if permissions are given.
    usage: /<command>
    permission: cex.home
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [home]
  cex_hyes:
    description: Confirms the /home iclear command and really deletes all homes found by it.
    usage: /<command>
    permission: cex.hyes
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [hyes]
  cex_kick:
    description: Kicks given player from the server, optionally providing a custom reason.
    usage: /<command> <Player> [reason]
    permission: cex.kick
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [kick]
  cex_mute:
    description: Mutes a player indefinitelly or for a given time period.
    usage: /<command> <Player> [time]
    permission: cex.mute
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [mute]
  cex_unmute:
    description: Unmutes a player.
    usage: /<command> <Player>
    permission: cex.unmute
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [unmute]
  cex_freeze:
    description: Freezes or unfreezes a player.
    usage: /<command> <Player>
    permission: cex.freeze
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [freeze]
  cex_warp:
    description: Teleports players to warp points and allows warp administration, if permissions are given.
    usage: /<command>
    permission: cex.warp
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [warp]
  cex_listwarps:
    description: Lists all available (public/private/own) warps on the server.
    usage: /<command>
    permission: cex.warp
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [listwarps]