author: Zathrus Writer
description: A set of commands and event handlers, built to per-request specs.
main: com.github.zathrus_writer.commandsex.CommandsEX
name: CommandsEX
load: postworld
version: '1.0'
website: http://dev.bukkit.org/server-mods/commandsex
permissions:
  cex.reload:
    default: op
    description: Allows player to reload CommandsEX configuration from disk (/cex reload).
  cex.tp:
    default: op
    description: Allows player to teleport himself to another player (/tp Player) and also one player to another (/tp Player1 Player2).
    children:
      cex.tpto: true
  cex.tpto:
    default: op
    description: Allows player to teleport himself to another player. (/tpto).
  cex.tphere:
    default: op
    description: Allows player to teleport another player to himself. (/tphere).
  cex.tploc:
    default: op
    description: Allows player to teleport himself to a specified location (/tploc).
  cex.lang:
    default: true
    description: Allows player to change their language and display list of available languages to change to.
  cex.spawn:
    default: true
    description: Allows player to instantly teleport to a spawn location.
  cex.setspawn:
    default: op
    description: Allows player to set server's spawn location.
  PlayerChatListener.replacechat:
    default: true
    description: Placeholder for event function that allows player chat text replacements.
  PlayerCommandListener.replaceplayercommand:
    default: true
    description: Placeholder for event function that allows player command replacements.
  ServerCommandListener.replaceconsolecommand:
    default: true
    description: Placeholder for event function that allows server (console) command replacements.
commands:
  cex:
    description: Displays version information and allows getting/setting configuration options.
    usage: |
           /<command>
           /<command> config -> lists available options
           /<command> config get <option>
           /<command> cg <option>
           /<command> config set <option> [add|remove <value>]
           /<command> cs <option> [add|remove <value>]
  cex_tp:
    description: Teleports one player to another.
    usage:  /<command> <Player1> [Player2]
    permission: cex.tp
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tp,tele,teleport,tp2p]
  cex_tpto:
    description: Teleports the active player to another player.
    usage: /<command> <Player>
    permission: cex.tpto
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tpto]
  cex_tphere:
    description: Teleports another player to the active player.
    usage: /<command> <Player>
    permission: cex.tphere
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tphere]
  cex_tploc:
    description: Teleports the player to the given XYZ coordinates.
    usage: |
           /<command> <X> <Y> <Z>
           /<command> <X,Y,Z>
    permission: cex.tploc
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [tploc]
  cex_lang:
    description: Displays list of available languages or changes language for the player.
    usage: /<command> [language]
    permission: cex.lang
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [lang]
  cex_spawn:
    description: Teleports a player to server's spawn location.
    usage: /<command>
    permission: cex.spawn
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [spawn]
  cex_setspawn:
    description: Sets the server's spawn location.
    usage: /<command>
    permission: cex.setspawn
    permission-message: You don't have sufficient permissions to use this command.
    aliases: [setspawn]